Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('LPKG_USING_MBEDTLS'):
    src += Glob('*.c')

group = DefineGroup('test-mbedtls', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
