from building import *

cwd = GetCurrentDir()
path  = [cwd]

src  = Glob('*.c')

mycflags = ' -w'
group = DefineGroup('lwIP', src, depend = ['RT_USING_LWIP'], CPPPATH = path,  LOCAL_CFLAGS = mycflags)

Return('group')
