Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_MMC_BARE_TEST'):
    src += Glob('test_mmc.c')

group = DefineGroup('test-mmc', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
