ctrl_interface=/var/run/wpa_supplicant
#device_name=Device A

##### IEEE 802.11ah related configuration #####################################


# s1g_capab: S1G capabilities (list of flags)
s1g_capab=[MAX-MPDU-7991] [S1G-LONG] [SUPPORTED-BW-0] [Rx-LDPC] [TX-STBC] [RX-STBC]
# [MAX-MPDU-7991]
#s1g_max_mpdu_len: [MAX-MPDU-3895]
# Indicates maximum MPDU length
# 0 = 3895 octets (default)
# 1 = 7991 octets

#normal beacon_int is the s1g short beacon int, don't add one more param for it
s1g_pv1_support=1
dot11S1GOptionImplemented=1

# s1g_capab: S1G capabilities (list of flags)
s1g_capab=[MAX-MPDU-7991] [S1G-LONG] [SUPPORTED-BW-0] [Rx-LDPC] [TX-STBC] [RX-STBC]
# [MAX-MPDU-7991]
#s1g_max_mpdu_len: [MAX-MPDU-3895]
# Indicates maximum MPDU length
# 0 = 3895 octets (default)
# 1 = 7991 octets

#The Max S1G-MCS for n SS subfield (where n=1,...,4) is encoded as follows:
#— 0 indicates support for S1G-MCS 2 for n spatial streams
#— 1 indicates support for S1G-MCS 7 for n spatial streams
#— 2 indicates support for S1G-MCS 9 for n spatial streams
#— 3 indicates that n spatial streams is not supported
#Rx S1GMCS Map
rx_s1g_mcs_map=0
#Rx Highest Supported Long GI Data Rate
s1g_rx_supported_long_gi_data_rate=0
#Tx S1GMCS Map
tx_s1g_mcs_map=0
#Tx Highest Supported Long GI Data Rate
s1g_tx_supported_long_gi_data_rate=0
#Rx Single Spatial Stream and S1G-MCS Map for 1 MHz
s1g_rx_mcs_1mhz=0
#Tx Single Spatial Stream and S1G-MCS Map for 1 MHz
s1g_tx_mcs_1mhz=0

network={
        ssid="s1g_test"
        key_mgmt=NONE
}
