Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_TP_BARE_TEST'):
    src += Glob('test_ctp.c')

group = DefineGroup('test-ctp', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
