Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = []

if GetDepend('AIC_USING_CAMERA'):
    CPPPATH.append(cwd)
    CPPPATH.append(cwd + '/common')
    src += Glob('common/*.c')

if GetDepend('AIC_USING_CAMERA_OV2640'):
    src += Glob('ov2640/*.c')

if GetDepend('AIC_USING_CAMERA_OV2659'):
    src += Glob('ov2659/*.c')

if GetDepend('AIC_USING_CAMERA_OV5640'):
    src += Glob('ov5640/*.c')

if GetDepend('AIC_USING_CAMERA_OV7670'):
    src += Glob('ov7670/*.c')

if GetDepend('AIC_USING_CAMERA_OV9281'):
    src += Glob('ov9281/*.c')

if GetDepend('AIC_USING_CAMERA_GC0308'):
    src += Glob('gc0308/*.c')

if GetDepend('AIC_USING_CAMERA_GC032A'):
    src += Glob('gc032a/*.c')

if GetDepend('AIC_USING_CAMERA_GM7150'):
    src += Glob('gm7150/*.c')

if GetDepend('AIC_USING_CAMERA_SC030IOT') or GetDepend('AIC_USING_CAMERA_SC031IOT'):
    src += Glob('sc030iot/*.c')

if GetDepend('AIC_USING_CAMERA_SC031GS'):
    src += Glob('sc031gs/*.c')

if GetDepend('AIC_USING_CAMERA_SC035HGS'):
    src += Glob('sc035/*.c')

if GetDepend('AIC_USING_CAMERA_TP2825') or GetDepend('AIC_USING_CAMERA_TP9950'):
    src += Glob('tp2825b/tp2825bx.c')

if GetDepend('AIC_USING_CAMERA_TP9951'):
    src += Glob('tp9951/tp9951.c')

if GetDepend('AIC_USING_CAMERA_N5'):
    src += Glob('N5/*.c')

LOCAL_CCFLAGS = ''
# LOCAL_CCFLAGS += ' -O0'

group = DefineGroup('ov5640', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CCFLAGS=LOCAL_CCFLAGS)

Return('group')
