/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Authors:  ArtInChip
 */


#include "ui_init.h"

void ui_init(void)
{
    lv_obj_t * label = lv_label_create(lv_scr_act());
    lv_label_set_text(label, "You can replace this code with the code generated by AiUIBuilder!");
    lv_obj_center(label);
}
