Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = []

if GetDepend('AIC_GYRO_SC7A20H'):
    CPPPATH.append(cwd)
    CPPPATH.append(cwd + '/sc7a20h')
    src += Glob('sc7a20h/*.c')

group = DefineGroup('gyro', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
