Import('AIC_ROOT')
Import('PRJ_KERNEL')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('realtek', src, depend = ['AIC_BT_REALTEK'], CPPPATH = CPPPATH)

Return('group')
