interface=wlan0
#bridge=br0
driver=nl80211
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
country_code=CN
hw_mode=ah
channel=1
dtim_period=2
max_num_sta=255
rts_threshold=-1
fragm_threshold=-1
supported_rates=300 600 900 1200 1800 2400 2700 3000 3600 4000
basic_rates=300 600 900 1200 1800 2400 2700 3000 3600 4000
macaddr_acl=0
auth_algs=3
ignore_broadcast_ssid=0
wmm_enabled=1
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
ieee80211n=0
require_ht=0

ieee80211ah=1
s1g_compatibility=0
rx_s1g_mcs_map=0
s1g_rx_supported_long_gi_data_rate=0
tx_s1g_mcs_map=0
s1g_tx_supported_long_gi_data_rate=0
s1g_rx_mcs_1mhz=0
s1g_tx_mcs_1mhz=0
require_s1g=1
compressed_ssid=test
s1g_oper_chwidth=1
s1g_operating_class=62
s1g_pri_chan=1
s1g_chan_center_freq=1
s1g_use_sta_nsts=0
s1g_basic_mcs_nsts=0
s1g_full_beacon_int=500
dot11S1GOptionImplemented=1
s1g_unscaled_interval=100
s1g_unified_scaling_factor=0
s1g_aid_switch_count=2

eapol_key_index_workaround=0
ssid=s1g_test
beacon_int=500
s1g_capab=[MAX-MPDU-7991] [S1G-LONG] [SUPPORTED-BW-0] [Rx-LDPC] [TX-STBC] [RX-STBC]
