Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_PSADC_TEST'):
    src += Glob('test_psadc.c')

group = DefineGroup('test-psadc', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
