Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_QSPI_DRV_TEST'):
    src += Glob('test_spi.c')

group = DefineGroup('test-spi', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
