Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src = []
group = []

if GetDepend(['AIC_WIFI_TEST']):
    src += Glob('./test_wifi.c')

group = DefineGroup('wifi-test', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
