Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('RT_USING_FINSH'):
    if GetDepend('RT_USING_MTD_NAND') and GetDepend('RT_MTD_NAND_DEBUG'):
        src = Glob('test_mtd.c')

group = DefineGroup('test-spinand', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
